/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-10-07 11:35:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.fasterxml.jackson.databind.ObjectMapper;

public final class digit_002dspan_002dpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/PC/.m2/repository/taglibs/standard/1.1.2/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098700290000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1723218410434L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.fasterxml.jackson.databind.ObjectMapper");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <html lang=\"en\" xmlns:c=\"http://java.sun.com/jsp/jstl/core\" xmlns:form=\"http://www.w3.org/1999/html\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <title>Digit Span Game</title>\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Afacad+Flux:wght@100..1000&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("        <style>\r\n");
      out.write("            body {\r\n");
      out.write("              font-family: Arial, sans-serif;\r\n");
      out.write("              display: flex;\r\n");
      out.write("              justify-content: center;\r\n");
      out.write("              align-items: center;\r\n");
      out.write("              height: 100vh;\r\n");
      out.write("              margin: 0;\r\n");
      out.write("              background-color: #f0f0f0;\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          .container {\r\n");
      out.write("               background-color: #dec5c5;\r\n");
      out.write("               padding: 20px;\r\n");
      out.write("               border-radius: 10px;\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          .action-group {\r\n");
      out.write("               display: flex;\r\n");
      out.write("               align-items: center;\r\n");
      out.write("               justify-content: space-between;\r\n");
      out.write("               margin-top: 40px;\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          .indicator {\r\n");
      out.write("               display: flex;\r\n");
      out.write("               border-radius: 10px;\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          .indic {\r\n");
      out.write("               width: 45px;\r\n");
      out.write("               height: 45px;\r\n");
      out.write("               margin-right: 10px;\r\n");
      out.write("               border-radius: 10px;\r\n");
      out.write("               border-style: double;\r\n");
      out.write("               display: flex;\r\n");
      out.write("               align-items: center;\r\n");
      out.write("               justify-content: center;\r\n");
      out.write("               padding: 0;\r\n");
      out.write("               box-sizing: border-box;\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          .start-btn, .reset-btn {\r\n");
      out.write("               font-family: \"Montserrat\", sans-serif;\r\n");
      out.write("               font-size: 18px;\r\n");
      out.write("               color: white;\r\n");
      out.write("               border-radius: 10px;\r\n");
      out.write("               border-style: none;\r\n");
      out.write("               padding: 5px 9px;\r\n");
      out.write("               box-sizing: border-box;\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          .start-btn {\r\n");
      out.write("               background-color: #2ba7f0;\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          .reset-btn {\r\n");
      out.write("\r\n");
      out.write("               background-color: red;\r\n");
      out.write("               padding: 7px 11px;\r\n");
      out.write("               box-sizing: border-box;\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          .user .check-btn {\r\n");
      out.write("               font-family: \"Montserrat\", sans-serif;\r\n");
      out.write("               width: 70px;\r\n");
      out.write("               padding-top: 7px;\r\n");
      out.write("               padding-bottom: 7px;\r\n");
      out.write("               font-size: 18px;\r\n");
      out.write("               border-radius: 10px;\r\n");
      out.write("               background-color: #5cdb35;\r\n");
      out.write("               border-style: none;\r\n");
      out.write("               color: white;\r\n");
      out.write("               margin-left: 15px;\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("            .check-btn:hover {\r\n");
      out.write("               background-color: #4cbd2a;\r\n");
      out.write("               transition: background-color 0.4s ease;\r\n");
      out.write("           }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            .user {\r\n");
      out.write("              display: flex;\r\n");
      out.write("              margin-top: 20px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            input{\r\n");
      out.write("              font-size: 20px;\r\n");
      out.write("              height: 40px;\r\n");
      out.write("              width: 400px;\r\n");
      out.write("              border-radius: 10px;\r\n");
      out.write("              border-style: none;\r\n");
      out.write("              padding: 10px;\r\n");
      out.write("              box-sizing: border-box;\r\n");
      out.write("              text-align: center;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("           .number-display {\r\n");
      out.write("              font-size: 22px;\r\n");
      out.write("              display: flex;\r\n");
      out.write("              justify-content: center;\r\n");
      out.write("              align-items: center;\r\n");
      out.write("              background-color: white;\r\n");
      out.write("              border-radius: 10px;\r\n");
      out.write("              height: 40px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .number-display .number {\r\n");
      out.write("              position: absolute;\r\n");
      out.write("              font-size: 25px;\r\n");
      out.write("              font-weight: 200;\r\n");
      out.write("              opacity: 0;\r\n");
      out.write("              animation: showNumber 1s linear forwards;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            @keyframes showNumber {\r\n");
      out.write("                0%, 100% { opacity: 0; }\r\n");
      out.write("                10%, 90% { opacity: 1; }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("            .number-display.hide-all .number {\r\n");
      out.write("                animation: none;\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            h1 {\r\n");
      out.write("              font-family: \"Montserrat\", sans-serif;\r\n");
      out.write("              font-optical-sizing: auto;\r\n");
      out.write("              font-weight: 300;\r\n");
      out.write("              font-style: normal;\r\n");
      out.write("              text-align: center;\r\n");
      out.write("              margin-bottom:50px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .action-group .form-select {\r\n");
      out.write("               font-family: \"Montserrat\", sans-serif;\r\n");
      out.write("               font-size: 15px;\r\n");
      out.write("               text-align:center;\r\n");
      out.write("               border-radius: 5px;\r\n");
      out.write("               padding: 2px 2px 2px 2px;\r\n");
      out.write("               margin-left: 70px;\r\n");
      out.write("               margin-top: 8px;\r\n");
      out.write("               width: 120px;\r\n");
      out.write("               height: 30px;\r\n");
      out.write("               font-weight: 500;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            input::placeholder {\r\n");
      out.write("                font-family: \"Montserrat\", sans-serif;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("    ");


        if (session.getAttribute("indicatorValue") == null) {
             session.setAttribute("indicatorValue", "1");
        }

        ArrayList<Integer> randomizedSequence = (ArrayList<Integer>) session.getAttribute("randomizedSequence");
        ObjectMapper objMapper = new ObjectMapper();
        String jsonData = objMapper.writeValueAsString(randomizedSequence);
        String indicatorValue = String.valueOf(session.getAttribute("indicatorValue"));
        String mode = String.valueOf(session.getAttribute("mode"));
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <h1>Digit Span</h1>\r\n");
      out.write("            <div class=\"number-display\">\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <form class=\"user\" action=\"numberCheck\" method=\"post\">\r\n");
      out.write("                <input class=\"userInput\" type=\"text\" name=\"userInput\" placeholder=\"Enter the Sequence\" oninput=\"convertToUpperCase(this)\" required disabled>\r\n");
      out.write("                <input type=\"hidden\" name=\"mode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.mode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                <button class=\"check-btn\" type=\"submit\">Check</button>\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"action-group\">\r\n");
      out.write("                <form class=\"indicator\" action=\"sequenceGeneration\" method=\"get\">\r\n");
      out.write("                    <input class=\"indic\" type=\"number\" name=\"indicatorValue\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty param.indicatorValue ? sessionScope.indicatorValue : param.indicatorValue}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" min=\"1\" max=\"100\" style=\"font-size: 20px;\">\r\n");
      out.write("                    <button class=\"start-btn\" type=\"submit\">Start</button>\r\n");
      out.write("                    <select name=\"mode\" id=\"mode\" class=\"form-select\">\r\n");
      out.write("                        <option value=\"Forwards\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty param.mode ? (sessionScope.mode == 'Forwards' ? 'selected' : '') : (param.mode == 'Forwards' ? 'selected' : '')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Forwards</option>\r\n");
      out.write("                        <option value=\"Backwards\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty param.mode ? (sessionScope.mode == 'Backwards' ? 'selected' : '') : (param.mode == 'Backwards' ? 'selected' : '')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Backwards</option>\r\n");
      out.write("                        <option value=\"Sequencing\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty param.mode ? (sessionScope.mode == 'Sequencing' ? 'selected' : '') : (param.mode == 'Sequencing' ? 'selected' : '')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Sequencing</option>\r\n");
      out.write("                        <option value=\"LetterNumberSequencing\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty param.mode ? (sessionScope.mode == 'LetterNumberSequencing' ? 'selected' : '') : (param.mode == 'LetterNumberSequencing' ? 'selected' : '')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Letter Number Sequencing</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("                <form action=\"resetIndicatorValue\" method=\"get\">\r\n");
      out.write("                    <button class=\"reset-btn\" type=\"submit\">Reset</button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            var randomizedSequence = ");
      out.print( jsonData );
      out.write(";\r\n");
      out.write("            var displayElement = document.querySelector(\".number-display\");\r\n");
      out.write("            var userInput = document.querySelector(\".userInput\");\r\n");
      out.write("            var checkButton = document.querySelector(\".check-btn\");\r\n");
      out.write("            var startButton = document.querySelector(\".start-btn\");\r\n");
      out.write("\r\n");
      out.write("            setTimeout(function() {\r\n");
      out.write("                displayElement.classList.add(\"hide-all\");\r\n");
      out.write("                userInput.disabled = false;\r\n");
      out.write("                checkButton.disabled = false;\r\n");
      out.write("            }, (randomizedSequence.length + 1) * 1000);\r\n");
      out.write("        </script>\r\n");
      out.write("        <script>\r\n");
      out.write("            function convertToUpperCase(input) {\r\n");
      out.write("                input.value = input.value.toUpperCase();\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("    </body>\r\n");
      out.write("    </html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /digit-span-page.jsp(144,12) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.randomizedSequence}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /digit-span-page.jsp(144,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("number");
      // /digit-span-page.jsp(144,12) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                .number-display .number:nth-child(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index + 1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(") {\r\n");
            out.write("                    animation-delay: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("s;\r\n");
            out.write("                }\r\n");
            out.write("            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /digit-span-page.jsp(204,16) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.randomizedSequence}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /digit-span-page.jsp(204,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("number");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                    <div class=\"number\"> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${number}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
